### PR TITLE
Probability Fixes

### PR DESCRIPTION
**Pull request by eylun**
Lecture 2:
- Minor typo adjustments and clarifications.

- Change to c.d.f definition

**Old:**
image

**New:**
image

- Fix to Variance formula

**Old:**
image

**New:**
image

### CODE REVIEW

**Comment by OliverKillane** [comment]
Good chance youve already found these & this is a redundant comment (in which case silly me for commenting on a draft pr)- but just in case.

The summation needs a subscript j instead of i. 
```tex
For a \keyword{discrete random variable} we define the probability mass function as:
\[p_X(x_i) = P(X = x_i) = P(E_i) \text{ where } x_i \in supp(X) \text{ and } x_i \text{ is the outcome of event } E_i\]
We can also define using \keyword{cfds}:
\[\left(F_X(x_i) = \sum_{j = 1}^ip_X(x_j)\right) \Leftrightarrow \left(p_X(x_i) = F_X(x_i) - F_X(x_{i-1}) \ \text{ where } i = 2, 3 \dots\right)\]
Or more simply:
\[p_X(x_i) = P_X(X = x_i) = P(X \leq x_i) - P(X \leq x_{i-1}) = F_X(x_i) - F_X(x_{i-1})\]
```
image

The missing squared on variance is a good spot - pretty elementary fuckup on my part, need to add it to the words above:
```tex
\termdef{Variance}{
The expected deviation from the squared expected/mean value.
\[Var(X) = Var_X(X) = \sigma_X^2 = E[(X - E(X))^2] = E(X^2) - (E(X))^2\]
Note that:
\[Var(a \times X + b) = a^2Var(X)\]
}
```
image

Sidenote:
There are a few places where I didnt use \left or \right to make brackets the right height, I will fix these in another commit after you're done with the draft & all is merged, unless you wanna.

**Comment by eylun** [comment]
Accidentally closed the PR on accident, my bad.

Anyway, about what you were saying, the current iteration I've got is something like this:
`\[F_X(x_i) = \sum^{i}_{j = 1}p_X(x_i) \Leftrightarrow p_X(x_i) = F_X(x_i) - F_X(x_{i-1}) \ \text{ where } i = 2, 3 \dots\]`

Regarding your commit, I'll put this branch out of draft tonight! You can make your commit after that. There are some minor changes in Lectures 3/4.

**Comment by OliverKillane** [comment]
> \sum^{i}_{j = 1}p_X(x_i)

(from prev comment) Should this not be `\sum^{i}_{j = 1}p_X(x_j)`

**Comment by eylun** [comment]
Ahh, yea you're absolutely right, I was looking at the wrong part of the formula, the change shall be made quickly!

Edit: ecba7c6

**Pull request merged**
